barrett:
  # Publish all joint states -------------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500
  
  # Position Controllers -----------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: proficio_joint_1
    pid: {p: 1200, i: 0, d: 5}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: proficio_joint_2
    pid: {p: 2000, i: 0, d: 5}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: proficio_joint_3
    pid: {p: 900, i: 0, d: 5}

  # Velocity Controllers -----------------------------------------
  joint1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: proficio_joint_1
    pid: {p: 42, i: 0, d: 0}

  joint2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: proficio_joint_2
    pid: {p: 18, i: 0, d: 0}

  joint3_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: proficio_joint_3
    pid: {p: 18, i: 0, d: 0}

  # Effort Controllers -----------------------------------------
  joint1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: proficio_joint_1

  joint2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: proficio_joint_2

  joint3_effort_controller:
    type: effort_controllers/JointEffortController
    joint: proficio_joint_3
