  # Publish all joint states -------------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500
 
  # Position - Velocity Controllers -----------------------------
  joint1_posvel_controller:
    type: barrett_controllers/JointPosVelController
    joint: proficio_left_joint_1
    pid: {p: 500, i: 0, d: 0.5} 

  joint2_posvel_controller:
    type: barrett_controllers/JointPosVelController
    joint: proficio_left_joint_2
    pid: {p: 1100, i: 0, d: 3} 

  joint3_posvel_controller:
    type: barrett_controllers/JointPosVelController
    joint: proficio_left_joint_3
    pid: {p: 120, i: 0, d: 0.5} 
 
  # Position Controllers -----------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: proficio_left_joint_1
    pid: {p: 10, i: 0, d: 0.5}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: proficio_left_joint_2
    pid: {p: 20, i: 0, d: 0.5}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: proficio_left_joint_3
    pid: {p: 2, i: 0, d: 0}

  # Velocity Controllers -----------------------------------------
  joint1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: proficio_left_joint_1
    pid: {p: 42, i: 0, d: 0}

  joint2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: proficio_left_joint_2
    pid: {p: 18, i: 0, d: 0}

  joint3_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: proficio_left_joint_3
    pid: {p: 18, i: 0, d: 0}

  # Effort Controllers -----------------------------------------
  joint1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: proficio_left_joint_1

  joint2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: proficio_left_joint_2

  joint3_effort_controller:
    type: effort_controllers/JointEffortController
    joint: proficio_left_joint_3

  # Trajectory Controller --------------------------------------
  trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - proficio_left_joint_1
      - proficio_left_joint_2
      - proficio_left_joint_3
   
    gains:
      proficio_left_joint_1: {p: 500, d: 0.5, i: 0, i_clamp: 0}
      proficio_left_joint_2: {p: 1100, d: 3, i: 0, i_clamp: 0}
      proficio_left_joint_3: {p: 120, d: 0.5, i: 0, i_clamp: 0}

    state_publish_rate: 500
