barrett:
  # Publish all joint states -------------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500
  
  # Position Controllers -----------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam_joint_1
    pid: {p: 900, i: 2.5, d: 10}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam_joint_2
    pid: {p: 2500, i: 5, d: 20}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam_joint_3
    pid: {p: 600, i: 2, d: 5}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam_joint_4
    pid: {p: 500, i: 0.5, d: 2}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam_joint_5
    pid: {p: 50, i: 0.5, d: 0.5}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam_joint_6
    pid: {p: 50, i: 0.5, d: 0.5}

  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam_joint_7
    pid: {p: 8, i: 0.1, d: 0.05}

  # Velocity Controllers -----------------------------------------
  joint1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wam_joint_1
    pid: {p: 42, i: 0, d: 0}

  joint2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wam_joint_2
    pid: {p: 42, i: 0, d: 0}

  joint3_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wam_joint_3
    pid: {p: 18, i: 0, d: 0}

  joint4_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wam_joint_4
    pid: {p: 18, i: 0, d: 0}

  joint5_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wam_joint_5
    pid: {p: 3, i: 0, d: 0}

  joint6_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wam_joint_6
    pid: {p: 3, i: 0, d: 0}

  joint7_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wam_joint_7
    pid: {p: 3, i: 0, d: 0.1}

  # Effort Controllers -----------------------------------------
  joint1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wam_joint_1

  joint2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wam_joint_2

  joint3_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wam_joint_3

  joint4_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wam_joint_4

  joint5_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wam_joint_5

  joint6_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wam_joint_6

  joint7_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wam_joint_7


